# Generated by Django 3.2.5 on 2021-07-31 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20210731_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_user',
            field=models.ManyToManyField(related_name='user_todo_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_todo_issue', to=settings.AUTH_USER_MODEL),
        ),
    ]
