# Generated by Django 3.2.5 on 2021-08-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_auto_20210802_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
